eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/sso/user


endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false